name: 🐛 Bug report
description: Report a bug or unexpected behavior
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve this project! Fill this out as best you can.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-sentence description of the problem.
      placeholder: "App crashes when I click Save"
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: Step-by-step instructions so we can see the bug too.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen instead?
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste any error messages or attach screenshots.
      render: shell
    validations:
      required: false
