name: ✨ Feature request
description: Suggest an idea or enhancement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Got an idea? Beautiful. Let’s capture it clearly.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short description of the feature.
      placeholder: "Add dark mode to the dashboard"
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why is this useful?
      description: How does this help you or other users?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe how you imagine this working.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other ways you thought about solving this.
    validations:
      required: false
